# Generated by Django 5.1.6 on 2025-03-05 08:04

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WardrobeApp', '0004_remove_userprofile_address_remove_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='rental_duration',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='rental_end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 12, 8, 4, 2, 167629, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='booking',
            name='rental_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(default='Employee', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('logid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WardrobeApp.login')),
            ],
        ),
    ]
