# Generated by Django 5.1.6 on 2025-03-07 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WardrobeApp', '0005_remove_booking_rental_duration_remove_employee_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='rental_end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 14, 9, 6, 15, 440702, tzinfo=datetime.timezone.utc)),
        ),
    ]
