# Generated by Django 5.1.6 on 2025-03-08 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WardrobeApp', '0010_remove_category_description_product_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AlterField(
            model_name='booking',
            name='rental_end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 15, 3, 44, 30, 932818, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('returned', 'Returned'), ('damaged', 'Damaged'), ('pending', 'Pending Approval')], default='available', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
