# Generated by Django 5.1.6 on 2025-03-08 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WardrobeApp', '0012_employee_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rental_end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 15, 17, 19, 7, 301635, tzinfo=datetime.timezone.utc)),
        ),
    ]
