# Generated by Django 5.1.6 on 2025-03-09 19:16

import WardrobeApp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WardrobeApp', '0013_employee_username_alter_booking_rental_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rental_duration',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rental_end_date',
            field=models.DateTimeField(default=WardrobeApp.models.default_rental_end_date),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(upload_to='employee_images/'),
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('returned', 'Returned'), ('damaged', 'Damaged'), ('pending', 'Pending Approval')], default='rented', max_length=10)),
                ('rented_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WardrobeApp.login')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WardrobeApp.product')),
            ],
        ),
    ]
