# Generated by Django 5.1.6 on 2025-03-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WardrobeApp', '0015_chatbotresponse_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='logid',
            new_name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
