# Generated by Django 5.1.6 on 2025-03-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WardrobeApp', '0016_rename_name_userprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
