# Generated by Django 5.1.6 on 2025-03-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WardrobeApp', '0025_feedback_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='product',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(default='no message'),
            preserve_default=False,
        ),
    ]
