# Generated by Django 5.1.6 on 2025-03-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WardrobeApp', '0026_remove_feedback_product_remove_feedback_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('casual', 'Casual'), ('formal', 'Formal'), ('party', 'Party Wear'), ('traditional', 'Traditional'), ('sportswear', 'Sportswear'), ('winter', 'Winter Wear')], default='casual', max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
