# Generated by Django 5.1.6 on 2025-03-24 05:22

import WardrobeApp.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WardrobeApp', '0031_alter_booking_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], default='M', max_length=5),
        ),
        migrations.AddField(
            model_name='cart',
            name='rental_end_date',
            field=models.DateField(default=WardrobeApp.models.default_rental_end_date),
        ),
        migrations.AddField(
            model_name='cart',
            name='rental_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], default='M', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], default='M', max_length=5),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rental_duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rental_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rental_start_date',
            field=models.DateField(),
        ),
    ]
