# Generated by Django 5.1.6 on 2025-03-24 09:55

import WardrobeApp.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WardrobeApp', '0032_booking_size_cart_rental_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='damage_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Refunded', 'Refunded'), ('Deducted', 'Deducted')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rental_end_date',
            field=models.DateField(default=WardrobeApp.models.default_rental_end_date),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rental_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cart',
            name='rental_end_date',
            field=models.DateField(default=WardrobeApp.models.default_rental_end_date),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('PayPal', 'PayPal'), ('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer'), ('Razorpay', 'Razorpay')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Pending', max_length=20),
        ),
    ]
