# Generated by Django 5.1.6 on 2025-03-27 04:52

import WardrobeApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WardrobeApp', '0038_alter_cart_rental_end_date_alter_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='rental_end_date',
            field=models.DateField(default=WardrobeApp.models.default_rental_end_date),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, default='M', max_length=50),
        ),
    ]
