# Generated by Django 5.1.6 on 2025-03-27 05:02

import WardrobeApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WardrobeApp', '0039_alter_cart_rental_end_date_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='rental_end_date',
            field=models.DateField(default=WardrobeApp.models.default_rental_end_date),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('casual', 'Casual'), ('formal', 'Formal'), ('party Wear', 'Party Wear'), ('traditional', 'Traditional'), ('sportswear', 'Sportswear'), ('winter', 'Winter Wear')], default='casual', max_length=20),
        ),
    ]
