# Generated by Django 5.1.6 on 2025-03-28 00:01

import WardrobeApp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WardrobeApp', '0043_alter_cart_rental_end_date_alter_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='rental_end_date',
            field=models.DateField(default=WardrobeApp.models.default_rental_end_date),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='WardrobeApp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WardrobeApp.login')),
            ],
        ),
    ]
