# Generated by Django 5.1.6 on 2025-03-28 00:26

import WardrobeApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WardrobeApp', '0044_alter_cart_rental_end_date_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotresponse',
            name='created_at',
        ),
        migrations.AddField(
            model_name='chatbotresponse',
            name='recommended_items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='rental_end_date',
            field=models.DateField(default=WardrobeApp.models.default_rental_end_date),
        ),
        migrations.AlterField(
            model_name='chatbotresponse',
            name='question',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='chatbotresponse',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
