# Generated by Django 5.1.6 on 2025-03-28 00:36

import WardrobeApp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WardrobeApp', '0045_remove_chatbotresponse_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='duration_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='rental',
            name='return_by',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='rental_end_date',
            field=models.DateField(default=WardrobeApp.models.default_rental_end_date),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('rented', 'Rented'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('canceled', 'Canceled')], default='rented', max_length=10),
        ),
        migrations.CreateModel(
            name='RentalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_duration_days', models.PositiveIntegerField(default=7)),
                ('accessories', models.TextField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental_info', to='WardrobeApp.product')),
            ],
        ),
    ]
