# Generated by Django 5.1.6 on 2025-03-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WardrobeApp', '0050_alter_rental_return_by_cart_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[(0, 'General Staff'), (1, 'Manager'), (2, 'Delivery Staff')], default='General Staff', max_length=150),
        ),
    ]
