# Generated by Django 5.1.6 on 2025-03-31 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WardrobeApp', '0052_employee_name_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('0', 'General Staff'), ('1', 'Manager'), ('2', 'Delivery Staff')], default='General Staff', max_length=150),
        ),
    ]
