# Generated by Django 5.1.6 on 2025-04-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WardrobeApp', '0054_remove_product_stock_booking_assigned_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrecommendation',
            name='recommendation_type',
            field=models.CharField(choices=[('accessory', 'Accessory'), ('complementary', 'Complementary Item'), ('matching', 'Matching Item')], default='accessory', max_length=20),
        ),
    ]
