# Generated by Django 5.1.6 on 2025-04-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WardrobeApp', '0058_booking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Rented'), (2, 'Returned'), (3, 'Overdue')], default=1),
        ),
        migrations.AlterField(
            model_name='return',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Damaged', 'Damaged'), ('Needs Cleaning', 'Needs Cleaning')], default='Good', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='productrecommendation',
            unique_together={('product', 'recommended_product', 'recommendation_type')},
        ),
    ]
