# Generated by Django 5.1.6 on 2025-04-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WardrobeApp', '0060_feedback_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
