# Generated by Django 5.1.6 on 2025-04-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WardrobeApp', '0061_alter_booking_booking_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tracking_status',
            field=models.CharField(choices=[('placed', 'Placed'), ('processing', 'Processing Started'), ('packed', 'Packed'), ('awaiting_pickup', 'Awaiting Pickup'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('return_scheduled', 'Return Pickup Scheduled'), ('returned', 'Returned')], default='placed', max_length=30),
        ),
    ]
