# Generated by Django 5.1.6 on 2025-04-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WardrobeApp', '0062_booking_tracking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='employee_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='refund_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
