# Generated by Django 5.1.6 on 2025-04-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WardrobeApp', '0063_return_employee_note_return_refund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='admin_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
