# Generated by Django 5.1.6 on 2025-04-09 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WardrobeApp', '0064_complaint_admin_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tracking_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_updates', to='WardrobeApp.employee'),
        ),
    ]
