# Generated by Django 5.1.6 on 2025-04-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WardrobeApp', '0065_booking_tracking_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='inspection_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='late_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tracking_status',
            field=models.CharField(choices=[('placed', 'Placed'), ('processing', 'Processing Started'), ('packed', 'Packed'), ('awaiting_pickup', 'Awaiting Pickup'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('return_scheduled', 'Return Pickup Scheduled'), ('returned', 'Returned'), ('refunded', 'Refunded')], default='placed', max_length=30),
        ),
    ]
