# Generated by Django 5.1.6 on 2025-04-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WardrobeApp', '0068_alter_productsize_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='tracking_status',
            field=models.CharField(choices=[('placed', 'Order Placed'), ('processing', 'Processing Started'), ('packed', 'Packed'), ('ready_for_pickup', 'Ready for Pickup'), ('delivered', 'Handed Over to Customer'), ('returned', 'Returned to Store'), ('refunded', 'Refund Processed')], default='placed', max_length=30),
        ),
    ]
