# Generated by Django 5.1.6 on 2025-04-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WardrobeApp', '0069_alter_booking_tracking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='bookings_made',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='items_added',
            field=models.IntegerField(default=0),
        ),
    ]
