# Generated by Django 5.1.6 on 2025-05-13 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WardrobeApp', '0072_alter_booking_return_by_alter_report_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='verified_by',
        ),
    ]
