# Generated by Django 5.1.6 on 2025-05-13 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WardrobeApp', '0073_remove_report_verified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='refund_status',
        ),
    ]
